builds:
- binary: NAMEinator
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm
  goarm:
  - 6
  - 7
  ldflags: >
    -X main.VERSION={{.Version}}
    -X main.DateBuilt={{.Date}}
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
